* Overview

This is a local Deep Research Agent that uses python-llama-cpp to run local models on your computer
to do research work. Multiple different research templates, server proxy to cut-off sub-agents after a couple of turns and
support for search backends like ddgs, arxiv, and wikipedia.

* Planned Tools

** search backends
- DuckDuckGo search (Done)
- Arxiv API 
- Google Scholar?
- Wikipedia API
- Reddit API (maybe specific subreddits)

** Tools
- Read and write files. 
- ls to see files.
- Claude Codes edit tool to iteratively edit reports

I am either going to have a limited tool set or just allow it to have a small bash environment that it can call into.
I am probably going to only have two search backends for now.
  
* Tool Proxy

Used to measure what tool calls each agent and sub-agent will be using and to cut-off model if we go near ctx window.
Include's Safety measures, because most harnesses will just preform illegal actions all the time with no ability to add rules, This is so it is pseudo-sandboxed on your system
with hard rules and on where you can read or write before executing tools, etc. To prevent unnecessary actions or downloading stuff you don't need.

* Research and Reasoning Modes to Implement

- Basic Research / Beginner learner format
- Medieval Disputates / dialectical
- basic syllogistic
- research more into other logical forms and formats

* Usage

This project is intended to do background work on whatever field or question you have and then compile a professional looking report for you to read later on.
Currently all the reports are in .org mode format as this is for my personal use, although changing the prompts and making the report .md and then using pandoc to compile
to latex shouldn't be hard.
