* Overview

This is a local Deep Research Agent that uses python-llama-cpp to run local models on your computer
to do research work. Multiple different research templates, server proxy to cut-off sub-agents after a couple of turns and
support for search backends like ddgs, arxiv, and wikipedia.

* Planned Tools

- DuckDuckGo search (Done)
- Arxiv API 
- Google Scholar?
- Wikipedia API
- Reddit API (maybe specific subreddits)
- Read and write files. 
- ls to see files

Some type of skill or tool to write and summarize entire research-task into a specific latex file report format.
The iterative approach is also good because we can just append to research task and then regenerate report if needed.
This is needed because local agents dont have massive context windows, speed, or flexibility. 
  
* Tool Proxy

Used to measure what tool calls each agent and sub-agent will be using and to cut-off model if we go near ctx window.
Include's Safety measures because most harnesses will just preform illegal actions all the time with no ability to add rules, This is so it is pseudo-sandboxed on your system
with hard rules and on where you can read or write before executing tools, etc. To prevent unnecessary actions or downloading

* Research and Reasoning Modes to Implement

- Basic Research / Beginner learner format
- Medieval Disputates / dialectical
- basic syllogistic
- research more into other logical forms

* Current Idea

Prompt Model -> consult search backends -> spawn subagents for specific tasks -> make tool calls -> go to tool-call proxy -> search and write to specified files if approved ->
Top level agent compiles report from all research into given template file.
